GET http://localhost:3000/iot/api/getLastIDt1
Accept: application/json

###
GET http://localhost:3000/iot/api/getLastIDt2
Accept: application/json

###
POST http://localhost:3000/iot/api/insertarValoresTabla1
Content-Type: application/json

{"boton": 0}

###
POST http://localhost:3000/iot/api/insertarValoresTabla2
Content-Type: application/json

{ "dist":150,
  "fotores":800 ,
  "fotoval":190 }

###
POST http://localhost:3000/iot/api/insertarValoresTabla3
Content-Type: application/json

{"tds": 70,
"tempe": 45}

###
GET http://10.22.201.178:3000/iot/api/getValoresTablaF?id=99
Accept: application/json

#http://10.22.201.178:3000/iot/api/

###
POST http://localhost:3000/iot/api/insertDistancias
Content-Type: application/json

{"distancia": 150.25}

###
POST http://localhost:3000/iot/api/getDistanciasByDate
Content-Type: application/json

{
  "date_one": "2024-10-30T00:00:00",
  "date_two": "2024-10-30T23:00:13"
}



###
GET http://10.22.201.178:3000/iot/api/getDistancias?id=99
Accept: application/json

###
POST http://localhost:3000/api/getDistancias
Content-Type: application/json

{
  "date_one": "2024-10-30T00:00:00",
  "date_two": "2024-10-30T23:00:13"
}

###

###

###
POST http://10.22.201.178:3000/iot/api/insertarValoresTabla1
Content-Type: application/json

{
  "boton": 1
}


###


POST http://localhost:3000/iot/api/getTemperatures
Content-Type: application/json

{
  "date_one": "2024-08-28T00:00:00",
  "date_two": "2024-08-28T23:00:13"
}




